name: Deploy to FreeHosting

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with FTP
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: ${{ github.repository }}
          branch: gh-pages
          folder: ./
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}

      - name: Push to gh-pages using Deploy Token
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/${{ github.repository }}.git
          git add .
          git commit -m "Deploying with GitHub Actions"
          git push origin gh-pages --force
