name: Deploy to FreeHosting

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with FTP
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: ${{ github.repository }}
          branch: gh-pages
          folder: ./
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
